# Set constants
EARTH_D=12742
EARTH_R=EARTH_D/2
EARTH_TILT=23.5
DATA_FILE_PATH="./data/debris.csv"
EARTH_IMAGE_PATH="./images/earth.jpg"
NUM_ORBITS_PLOTTED=100
MINUTES_IN_YEAR=525600
SOLAR_CONS  TANT=1361
YEARLY_KW_SCALE=8760
PLOT_ORBITS=True
PLOT_ENERGY=False